# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-cloud'
    organization: 'mcmejia1'
    scannerMode: 'CLI'
    configMode: 'file'

- script: |
    npm run test:coverage
  displayName: 'Run unit Test'
  condition: succeeded()

- task: SonarCloudAnalyze@1
  displayName: 'Sonar Analysis'
  condition: succeeded()

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate'
  inputs:
    pollingTimeoutSec: '300'

- script: |
    npm rebuild
    npm run build --skip-test --if-present 
  displayName: 'npm build'

- task: ArchiveFiles@2
  displayName: 'Zip api folder'
  inputs:
    rootFolderOrFile: 'api'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/api.zip'
    replaceExistingArchive: false

- task: ArchiveFiles@2
  displayName: 'Zip package.json'
  inputs:
    rootFolderOrFile: 'package.json'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/api.zip'
    replaceExistingArchive: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/api.zip'
    ArtifactName: 'artifact'
    publishLocation: 'Container'
  displayName: 'Publishing artifact'